name: maps_tracking_toolbox
description: "A Flutter package providing utility functions for real-time location tracking, distance calculations, and route management for maps-based applications."
version: 0.0.7
homepage: "https://github.com/isaiah-code/maps_tracking_tools"

environment:
  sdk: ^3.5.3
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  geolocator: ^14.0.2
  google_maps_flutter: ^2.13.1
  location: ^8.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
